#!/bin/bash

artist=$(cmus-remote -Q|grep artist)
song=$(cmus-remote -Q|grep title)
condition=$(cmus-remote -Q|grep status)
#echo $artist
#echo $song
#echo $condition
name=$(echo $song|awk '
{
	for(i=3; i<=NF; i++)
		printf("%s ",$i);
}')
singer=$(echo $artist|awk '
{
	for(i=3; i<=NF; i++)
		printf("%s ",$i);
}')
label=$( echo $condition|awk '{printf("%s",$2);}')
if [[ "$label" == "playing" ]]
then
	echo "$singer- $name"
else
	echo "Paused"
fi
