#!/bin/bash

artist=$(cmus-remote -Q|grep -w artist)
song=$(cmus-remote -Q|grep -w title)
condition=$(cmus-remote -Q|grep -w status)
#echo $artist
#echo $song
#echo $condition
name=$(echo $song|awk '
{
	for(i=3; i<=NF; i++)
		printf("%s ",$i);
}')
singer=$(echo $artist|awk '
{
	for(i=3; i<=NF; i++)
		printf("%s ",$i);
}')
#bold=$(tput bold)
#normal=$(tput sgr0)
#tput bold
label=$( echo $condition|awk '{printf("%s",$2);}')
if [[ "$label" == "playing" ]]
then
	echo " [ $singer- $name ]"
else
	echo " [ Paused ]"
fi
